# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='nombre',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
