# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plantilla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extintores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etiqueta', models.BooleanField()),
                ('seguro', models.BooleanField()),
                ('pintura', models.BooleanField()),
                ('valvula', models.BooleanField()),
                ('nanometro', models.BooleanField()),
                ('peso', models.BooleanField()),
                ('nanguera', models.BooleanField()),
                ('señalamiento', models.BooleanField()),
                ('altura', models.BooleanField()),
                ('proteccion', models.BooleanField()),
                ('operable', models.BooleanField()),
                ('obstruido', models.BooleanField()),
                ('ultima_reca', models.DateTimeField()),
                ('vencimiento', models.DateField(default=django.utils.timezone.now)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantilla.Empleados')),
            ],
            options={
                'verbose_name_plural': 'Extintores',
            },
        ),
    ]
