# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_terceros', '0002_auto_20170127_1104'),
        ('inspecciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extintores',
            name='extintor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario_terceros.Extintores'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extintores',
            name='ultima_reca',
            field=models.DateTimeField(verbose_name='Ultima Recarga'),
        ),
    ]
