# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-19 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extintores',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
