# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0002_auto_20170127_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extintores',
            old_name='nanguera',
            new_name='manguera',
        ),
        migrations.AddField(
            model_name='extintores',
            name='fecha_revision',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
