# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0003_auto_20170127_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='extintores',
            name='observaciones',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
