# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0006_extintores_limpieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='extintores',
            name='foto',
            field=models.ImageField(default=1, upload_to='static/images/inspecciones/observaciones'),
            preserve_default=False,
        ),
    ]
