# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0008_auto_20170212_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extintores',
            name='foto',
            field=models.ImageField(blank=True, upload_to='static/images/inspecciones/observaciones'),
        ),
        migrations.AlterField(
            model_name='extintores',
            name='status',
            field=models.CharField(choices=[('En su lugar', 'En su lugar'), ('No Encontrado', 'No Encontrado'), ('Reemplazado por caducidad', 'Reemplazado por caducidad'), ('Reemplazado por falta de presion', 'Reemplazado por falta de presion')], max_length=140),
        ),
    ]
