# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0011_auto_20170221_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='extintores',
            name='acciones_nanometro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extintores',
            name='acciones_peso',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extintores',
            name='acciones_pintura',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extintores',
            name='acciones_valvula',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extintores',
            name='arreglo_nanometro_sitio',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extintores',
            name='arreglo_peso_sitio',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extintores',
            name='arreglo_pintura_sitio',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extintores',
            name='arreglo_valvula_sitio',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extintores',
            name='condicion_nanometro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extintores',
            name='condicion_peso',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extintores',
            name='condicion_pintura',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extintores',
            name='condicion_valvula',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extintores',
            name='foto_nanometro_antes',
            field=models.ImageField(blank=True, upload_to='static/images/inspecciones/reportes/antes/nanometro'),
        ),
        migrations.AddField(
            model_name='extintores',
            name='foto_nanometro_despues',
            field=models.ImageField(blank=True, upload_to='static/images/inspecciones/reportes/despues/nanometro'),
        ),
        migrations.AddField(
            model_name='extintores',
            name='foto_peso_antes',
            field=models.ImageField(blank=True, upload_to='static/images/inspecciones/reportes/antes/peso'),
        ),
        migrations.AddField(
            model_name='extintores',
            name='foto_peso_despues',
            field=models.ImageField(blank=True, upload_to='static/images/inspecciones/reportes/despues/peso'),
        ),
        migrations.AddField(
            model_name='extintores',
            name='foto_pintura_antes',
            field=models.ImageField(blank=True, upload_to='static/images/inspecciones/reportes/antes/pintura'),
        ),
        migrations.AddField(
            model_name='extintores',
            name='foto_pintura_despues',
            field=models.ImageField(blank=True, upload_to='static/images/inspecciones/reportes/despues/pintura'),
        ),
        migrations.AddField(
            model_name='extintores',
            name='foto_valvula_antes',
            field=models.ImageField(blank=True, upload_to='static/images/inspecciones/reportes/antes/valvula'),
        ),
        migrations.AddField(
            model_name='extintores',
            name='foto_valvula_despues',
            field=models.ImageField(blank=True, upload_to='static/images/inspecciones/reportes/despues/valvula'),
        ),
        migrations.AddField(
            model_name='extintores',
            name='motivos_nanometro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extintores',
            name='motivos_peso',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extintores',
            name='motivos_pintura',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extintores',
            name='motivos_valvula',
            field=models.TextField(blank=True),
        ),
    ]
