# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0014_auto_20170221_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extintores',
            name='ultima_reca',
        ),
        migrations.RemoveField(
            model_name='extintores',
            name='vencimiento',
        ),
    ]
