# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planteles', '0001_initial'),
        ('plantilla', '0005_auto_20170223_1436'),
        ('inspecciones', '0015_auto_20170224_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.CharField(choices=[('01', 'Enero'), ('02', 'Febero'), ('03', 'Marzo')], max_length=10)),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planteles.Areas')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantilla.Empleados')),
            ],
            options={
                'verbose_name': 'Asignacion',
                'verbose_name_plural': 'Asignaciones',
            },
        ),
        migrations.AlterField(
            model_name='extintores',
            name='status',
            field=models.CharField(choices=[('En su lugar', 'En su lugar'), ('No Encontrado', 'No Encontrado'), ('Reemplazado por caducidad', 'Reemplazado por caducidad'), ('Reemplazado por daño', 'Reemplazado por daño'), ('Reemplazado por falta de presion', 'Reemplazado por falta de presion'), ('Sin acceso al area', 'Sin acceso al area')], max_length=140),
        ),
    ]
