# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0016_auto_20170225_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciones',
            name='año',
            field=models.CharField(default=2017, max_length=4),
        ),
    ]
