# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planteles', '0001_initial'),
        ('plantilla', '0005_auto_20170223_1436'),
        ('inspecciones', '0017_asignaciones_año'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignaciones',
            unique_together=set([('area', 'empleado', 'mes', 'año')]),
        ),
    ]
