# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0018_auto_20170302_0921'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asignaciones',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='asignaciones',
            name='area',
        ),
    ]
