# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0019_auto_20171112_0301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extintores',
            options={'verbose_name': 'Extintor', 'verbose_name_plural': 'Extintores'},
        ),
    ]
