# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspecciones', '0020_auto_20171112_0314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extintores',
            options={'verbose_name': 'Inspeccion a Extintor', 'verbose_name_plural': 'Inspecciones a Extintores'},
        ),
    ]
