# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 03:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carteras', '0006_auto_20171110_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('unidad_medida', models.CharField(blank=True, max_length=100, verbose_name='Unidad de Medida')),
                ('precio_proveedor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('precio_publico', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_maximo', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('existencia', models.IntegerField()),
                ('exposicion', models.IntegerField()),
                ('fecha_alta', models.DateField(default=datetime.datetime.today)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteras.Proveedores')),
            ],
        ),
    ]
