# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 05:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('carteras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidad de Medida')),
                ('precio_proveedor', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('precio_publico', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('stock_maximo', models.IntegerField(blank=True, null=True)),
                ('stock_minimo', models.IntegerField(blank=True, null=True)),
                ('existencia', models.IntegerField(blank=True, null=True)),
                ('exposicion', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, upload_to='static/images/productos')),
                ('fecha_alta', models.DateField(default=datetime.datetime.today)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.CategoriaProductos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteras.Proveedores')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
