# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cacesi', '0002_auto_20171110_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidad de Medida'),
        ),
    ]
