# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cacesi', '0003_auto_20171110_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precio_proveedor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio_publico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
