# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cacesi', '0004_auto_20171110_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='existencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='exposicion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock_maximo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock_minimo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
