# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cacesi', '0005_auto_20171110_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.CharField(blank=True, choices=[('2', 'Proteccion Ocular'), ('1', 'Proteccion Para la Cabeza'), ('3', 'Proteccion Respiratoria')], max_length=100),
        ),
    ]
