# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cacesi', '0006_productos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(blank=True, choices=[('2', 'Proteccion Ocular'), ('3', 'Proteccion Respiratoria'), ('1', 'Proteccion Para la Cabeza')], max_length=100),
        ),
    ]
