# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cacesi', '0008_auto_20171111_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='foto',
            field=models.ImageField(blank=True, upload_to='static/images/productos'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(blank=True, choices=[('3', 'Proteccion Respiratoria'), ('2', 'Proteccion Ocular'), ('1', 'Proteccion Para la Cabeza')], max_length=100),
        ),
    ]
