# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cacesi', '0011_auto_20171112_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(blank=True, choices=[('3', 'Proteccion Respiratoria'), ('1', 'Proteccion Para la Cabeza'), ('2', 'Proteccion Ocular')], max_length=100),
        ),
        migrations.DeleteModel(
            name='CategoriaProductos',
        ),
    ]
