# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cacesi', '0012_auto_20171112_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
