# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cacesi', '0014_auto_20171112_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario_cacesi.CategoriaProductos'),
        ),
    ]
