# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cacesi', '0018_auto_20171112_0036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproductos',
            options={'verbose_name_plural': 'Categorias de Productos'},
        ),
    ]
