# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_cacesi', '0020_auto_20171112_0314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
