# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_categoriaproductos'),
        ('inventario_cacesi', '0021_auto_20171112_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogos.CategoriaProductos'),
            preserve_default=False,
        ),
    ]
