# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 05:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140)),
                ('razon_social', models.CharField(max_length=140)),
                ('rfc', models.CharField(max_length=20)),
                ('sucursal', models.CharField(max_length=140)),
                ('codigo', models.CharField(max_length=20)),
                ('giro', models.CharField(max_length=140)),
                ('calle', models.CharField(max_length=140)),
                ('colonia', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=140)),
                ('estado', models.CharField(max_length=60)),
                ('pais', models.CharField(default='Mexico', max_length=60)),
                ('region', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
                ('pagina_web', models.CharField(blank=True, max_length=140)),
                ('logo', models.ImageField(blank=True, upload_to='static/images/logosClientes')),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Contactos_Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('telefono_oficina', models.CharField(blank=True, max_length=12)),
                ('extension', models.IntegerField(blank=True, null=True)),
                ('celular', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_alta', models.DateField(default=datetime.datetime.today)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteras.Clientes')),
            ],
            options={
                'verbose_name_plural': 'Contactos del Cliente',
            },
        ),
        migrations.CreateModel(
            name='Contactos_Proveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('telefono_oficina', models.CharField(blank=True, max_length=12)),
                ('celular', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_alta', models.DateField(default=datetime.datetime.today)),
            ],
            options={
                'verbose_name_plural': 'Contactos del Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=12)),
                ('pagina_web', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('fecha_registro', models.DateField(default=datetime.datetime.today)),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42)),
                ('giro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.GiroProveedores')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.AddField(
            model_name='contactos_proveedores',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteras.Proveedores'),
        ),
    ]
