# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140)),
                ('razon_social', models.CharField(max_length=140)),
                ('rfc', models.CharField(max_length=20)),
                ('sucursal', models.CharField(max_length=140)),
                ('codigo', models.CharField(max_length=20)),
                ('giro', models.CharField(max_length=140)),
                ('calle', models.CharField(max_length=140)),
                ('municipio', models.CharField(max_length=140)),
                ('estado', models.CharField(max_length=60)),
                ('pais', models.CharField(default='Mexico', max_length=60)),
                ('region', models.IntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
                ('pagina_web', models.CharField(max_length=140)),
                ('logo', models.ImageField(upload_to='static/logosClientes')),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
