# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteras', '0002_clientes_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('giro', models.CharField(choices=[(2, 'Equipos Contra Incendios'), (1, 'Maquinaria'), (3, 'Equipos de Seguridad')], max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=12)),
                ('pagina_web', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('fecha_registro', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
