# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-19 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carteras', '0003_clientes_cp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedores',
            name='giro',
        ),
    ]
