# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 02:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carteras', '0004_auto_20171110_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos_Proveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('telefono_oficina', models.CharField(blank=True, max_length=12)),
                ('celular', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_alta', models.DateField(default=datetime.datetime.today)),
            ],
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='giro',
            field=models.CharField(choices=[(3, 'Equipos de Seguridad'), (1, 'Maquinaria'), (2, 'Equipos Contra Incendios')], max_length=100),
        ),
        migrations.AddField(
            model_name='contactos_proveedores',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteras.Proveedores'),
        ),
    ]
