# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteras', '0006_auto_20171110_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='giro',
            field=models.CharField(choices=[('1', 'Maquinaria'), ('3', 'Equipos de Seguridad'), ('2', 'Equipos Contra Incendios')], max_length=100),
        ),
    ]
