# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteras', '0010_auto_20171110_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='giro',
            field=models.CharField(choices=[('3', 'Equipos de Seguridad'), ('2', 'Equipos Contra Incendios'), ('1', 'Maquinaria')], max_length=100),
        ),
    ]
