# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carteras', '0011_auto_20171111_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='colonia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
    ]
