# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('carteras', '0012_auto_20171111_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='logo',
            field=models.ImageField(blank=True, upload_to='static/logosClientes'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pagina_web',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='giro',
            field=models.CharField(choices=[('1', 'Maquinaria'), ('3', 'Equipos de Seguridad'), ('2', 'Equipos Contra Incendios')], max_length=100),
        ),
    ]
