# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-11 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteras', '0014_auto_20171111_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='giro',
            field=models.CharField(choices=[('2', 'Equipos Contra Incendios'), ('3', 'Equipos de Seguridad'), ('1', 'Maquinaria')], max_length=100),
        ),
    ]
