# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 02:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carteras', '0022_auto_20171112_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos_Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('puesto', models.CharField(blank=True, max_length=100)),
                ('telefono_oficina', models.CharField(blank=True, max_length=12)),
                ('extension', models.IntegerField(blank=True, null=True)),
                ('celular', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_alta', models.DateField(default=datetime.datetime.today)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteras.Clientes')),
            ],
            options={
                'verbose_name_plural': 'Contactos del Cliente',
            },
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='giro',
            field=models.CharField(choices=[('3', 'Equipos de Seguridad'), ('1', 'Maquinaria'), ('2', 'Equipos Contra Incendios')], max_length=100),
        ),
    ]
