# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteras', '0028_auto_20171112_0319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='proveedores',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='giro',
            field=models.CharField(choices=[('1', 'Maquinaria'), ('3', 'Equipos de Seguridad'), ('2', 'Equipos Contra Incendios')], max_length=100),
        ),
    ]
