# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carteras', '0002_clientes_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('plano', models.FileField(upload_to='static/files/areas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteras.Clientes')),
            ],
            options={
                'verbose_name_plural': 'Areas',
            },
        ),
    ]
