# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carteras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extintores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=140)),
                ('ubicacion', models.CharField(max_length=140)),
                ('no_control', models.CharField(max_length=140)),
                ('tipo_extintor', models.CharField(max_length=140)),
                ('clasificacion', models.CharField(max_length=140)),
                ('capacidad', models.CharField(max_length=140)),
                ('foto', models.ImageField(upload_to='static/images/extintores')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteras.Clientes')),
            ],
        ),
    ]
