# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('carteras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extintores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=140)),
                ('no_control', models.CharField(max_length=140)),
                ('tipo_extintor', models.CharField(choices=[('AGUA', 'AGUA'), ('AGUA CON ESPUMA', 'AGUA CON ESPUMA'), ('Co2', 'Co2'), ('CLASE D', 'CLASE D'), ('CLASE K', 'CLASE K'), ('HALOTRON', 'HALOTRON'), ('PQS', 'PQS')], max_length=140)),
                ('clasificacion', models.CharField(choices=[('Automotriz', 'Automotriz'), ('Movil', 'Movil'), ('Poratil', 'Portatil')], max_length=140)),
                ('capacidad', models.CharField(choices=[('Kg', 'Kilogramos'), ('Lts', 'Litros')], max_length=140)),
                ('contenido_neto', models.CharField(choices=[('3/4', '3/4'), ('1', '1'), ('2', '2'), ('2.5', '2.5'), ('4.5', '4.5'), ('6', '6'), ('6.8', '6.8'), ('9', '9'), ('10', '10'), ('12', '12'), ('22', '22'), ('34', '34'), ('45', '45'), ('50', '50'), ('68', '68')], max_length=100)),
                ('ultima_reca', models.DateField(default=django.utils.timezone.now, verbose_name='Ultima Recarga')),
                ('vencimiento', models.DateField()),
                ('foto', models.ImageField(blank=True, upload_to='static/images/extintores')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.Areas')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carteras.Clientes')),
            ],
            options={
                'verbose_name': 'Extintor',
                'verbose_name_plural': 'Extintores',
            },
        ),
    ]
