# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-14 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_terceros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extintores',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extintores',
            name='no_control',
            field=models.CharField(blank=True, max_length=140, unique=True),
        ),
    ]
