# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-19 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_terceros', '0002_auto_20171114_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extintores',
            name='cliente',
        ),
    ]
