# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-20 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('carteras', '0004_remove_proveedores_giro'),
        ('inventario_terceros', '0003_remove_extintores_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='extintores',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carteras.Clientes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extintores',
            name='area',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='cliente', chained_model_field='cliente', on_delete=django.db.models.deletion.CASCADE, to='catalogos.Areas'),
        ),
    ]
