# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_terceros', '0004_auto_20170131_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extintores',
            name='area',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='extintores',
            name='capacidad',
            field=models.CharField(choices=[('2.5', '2.5'), ('4.5', '4.5'), ('6', '6'), ('9', '9'), ('34', '34'), ('50', '50')], max_length=140),
        ),
        migrations.AlterField(
            model_name='extintores',
            name='tipo_extintor',
            field=models.CharField(choices=[('CO2', 'CO2'), ('PQS', 'PQS'), ('TIPO K', 'TIPO K')], max_length=140),
        ),
        migrations.DeleteModel(
            name='Areas',
        ),
    ]
