# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_terceros', '0005_auto_20170217_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extintores',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planteles.Areas'),
        ),
    ]
