# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 22:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_terceros', '0006_auto_20170217_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='extintores',
            name='ultima_reca',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ultima Recarga'),
        ),
        migrations.AddField(
            model_name='extintores',
            name='vencimiento',
            field=models.DateField(default=datetime.datetime(2018, 2, 24, 22, 30, 41, 696254, tzinfo=utc)),
        ),
    ]
