# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_terceros', '0010_auto_20170224_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extintores',
            name='vencimiento',
            field=models.DateField(),
        ),
    ]
