# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_terceros', '0011_auto_20170224_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extintores',
            name='cliente',
        ),
    ]
