# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_terceros', '0012_remove_extintores_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extintores',
            options={'verbose_name': 'Extintor', 'verbose_name_plural': 'Extintores'},
        ),
    ]
