# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carteras', '0024_auto_20171112_0251'),
        ('inventario_terceros', '0014_auto_20171110_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extintores',
            name='area',
        ),
        migrations.AddField(
            model_name='extintores',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carteras.Clientes'),
            preserve_default=False,
        ),
    ]
