# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('inventario_terceros', '0015_auto_20171112_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='extintores',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogos.Areas'),
            preserve_default=False,
        ),
    ]
