# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_terceros', '0016_extintores_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='extintores',
            name='contenido_neto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='extintores',
            name='capacidad',
            field=models.CharField(choices=[('Kg', 'Kilogramos'), ('Lts', 'Litros')], max_length=140),
        ),
        migrations.AlterField(
            model_name='extintores',
            name='clasificacion',
            field=models.CharField(choices=[('Automotriz', 'Automotriz'), ('Movil', 'Movil'), ('Poratil', 'Portatil')], max_length=140),
        ),
        migrations.AlterField(
            model_name='extintores',
            name='tipo_extintor',
            field=models.CharField(choices=[('AGUA', 'AGUA'), ('AGUA CON ESPUMA', 'AGUA CON ESPUMA'), ('Co2', 'Co2'), ('CLASE D', 'CLASE D'), ('CLASE K', 'CLASE K'), ('HALOTRON', 'HALOTRON'), ('PQS', 'PQS')], max_length=140),
        ),
    ]
