# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_terceros', '0017_auto_20171112_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extintores',
            name='contenido_neto',
            field=models.CharField(choices=[('3/4', '3/4'), ('1', '1'), ('2', '2'), ('2.5', '2.5'), ('4.5', '4.5'), ('6', '6'), ('6.8', '6.8'), ('9', '9'), ('10', '10'), ('12', '12'), ('22', '22'), ('34', '34'), ('45', '45'), ('50', '50'), ('68', '68')], max_length=100),
        ),
    ]
