# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-12 05:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140)),
                ('apellidos', models.CharField(max_length=140)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=140)),
                ('ciudad', models.CharField(max_length=140)),
                ('estado', models.CharField(default='Durango', max_length=140)),
                ('cp', models.IntegerField()),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now)),
                ('foto', models.ImageField(upload_to='static/images/team')),
                ('perfil', models.IntegerField(choices=[(1, 'Inspector'), (2, 'Supervisor'), (3, 'Capacitador')])),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
