# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140)),
                ('apellidos', models.CharField(max_length=140)),
                ('edad', models.IntegerField()),
                ('direccion', models.CharField(max_length=140)),
                ('ciudad', models.CharField(max_length=140)),
                ('estado', models.CharField(max_length=140)),
                ('cp', models.IntegerField()),
                ('telefono', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_alta', models.DateTimeField()),
            ],
        ),
    ]
