# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0002_auto_20170127_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='foto',
            field=models.ImageField(default=1, upload_to='static/images/team'),
            preserve_default=False,
        ),
    ]
