# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plantilla', '0003_empleados_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='perfil',
            field=models.CharField(choices=[(1, 'Inspector'), (2, 'Supervisor'), (3, 'Capacitador')], default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleados',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
