# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0004_auto_20170223_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='perfil',
            field=models.IntegerField(choices=[(1, 'Inspector'), (2, 'Supervisor'), (3, 'Capacitador')]),
        ),
    ]
