# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plantilla', '0005_auto_20170223_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='estado',
            field=models.CharField(default='Durango', max_length=140),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='fecha_alta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='telefono',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
